<h2>Agregar Tarea</h2>

<form action="">
    <p>
        <label for="nombre">Nombre: </label>
        <input type="text" name="nombre">
    </p>

    <p>
        <label for="descripcion">Descripcion: </label>
        <input type="textarea" name="descripcion">
    </p>

    <p>
        <label for="descripcion">Categoría: </label>
        <select name="" id="">
            <?php
                foreach($categorias as $categoria): ?>
                    <option value="<?php echo $categoria['id'];?>">
                        <?php echo $categoria['nombre'];?>
                    </option>;
            <?php endforeach;
            ?>
        </select>
    </p>
</form>

