
<h2>Lista de tareas</h2>
<table>
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Categoría</th>
        <th>Fecha</th>
        <th>Prioridad</th>
        <th>Status</th>
        <th>Acción</th>
    </tr>
    <?php foreach ($tareas as $tarea):?>

    <tr>
        <td><?php echo $tarea["tareas"]["id"]; ?></td>
        <td><?php echo $tarea["tareas"]["nombre"]; ?></td>
        <td><?php echo $tarea["tareas"]["descripcion"]; ?></td>

        <td><?php echo $tarea["categorias"]["nombre"]; ?></td>
        <td><?php echo $tarea["tareas"]["fecha"]; ?></td>
        <td><?php echo $tarea["tareas"]["prioridad"]; ?></td>
        <td><?php echo $tarea["tareas"]["status"]; ?></td>
        <td>
            <?php
                echo $this->Html->link(
                    "Editar",
                    array(
                        "controller"=>"tareas",
                        "method"=>"editar",
                        "args"=>$tarea["tareas"]["id"]
                    ),
                    array(
                        "title"=>"Editar tarea"

                    )
                );

                echo " | ";
                echo  $this->Html->link(
                    "Elimiar",
                    array(
                        "controller"=>"tareas",
                        "method"=>"eliminar",
                        "args"=>$tarea["tareas"]["id"]
                    )
                );
            ?>
        </td>
    </tr>
<?php endforeach; ?>

</table>